### ISSUE TITLE
Create GameQuestion Page (a page where questions are shown one by one)

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-client#20]
- [x] #21
- [x] #22
- [ ] #23
- [x] #24

**Comment by NattiShakira** [comment]
Additional tasks to be done:
- check dependencies arrays in useEffect hooks on this page;
- make the right answer to turn into green after ~20 seconds, then after ~10 more sec. automatic rerouting; 
- a user cannot click an answer after the right answer is displayed;
- add countdown.

**Comment by NattiShakira** [comment]
Commits:
- client: 95a90c6a591e93f7f4e9bbdbf7e6f222dd43b13d
- server: 3620d95597891a50bc030ebf6dbe0a98bbe5eab6
