### ISSUE TITLE
Add custom styling to all the pages

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-client#70]
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82

**Comment by florencehuegi** [comment]
3ce2ff8e51a0c965322467a620f0aa1ff674d688
b33f019013f362ef79ccc18531bb8068eee79ec8
5e1ffe5cd9f7211247ff27e7f53928d1eeaa93fd
2a5c18deb70fce23eef86e7cc6f6cffe2fbea2dd
a822c6954979a09a69bb48adfbb6910f7a18caa6
eeae0bc0fc423e6a77b20558ad889bf5ae2f0d3d
c86a9ef349ca6a1c464c8d94f1cf3b23e8395ce6
a7d9cb1cb0e9443d1d9d5373000b649590378a1d
